Add sync modes to Sailthru destination plugin.
grouparoo/grouparoo pull request #1785
Opened 2021-05-13 02:28 UTC by pauloouriques

2021-05-14 14:48 UTC, pedroslopez requested changes
Looking good! I don't see any tests for the case where the sync mode doesn't allow deleting. We should probably add some for that.

2021-05-17 23:20 UTC, pedroslopez approved these changes

2021-05-17 23:30 UTC, evantahler requested changes
Good work overall!

There's some scrubbing in the nockfiles to do, which we can talk about in Slack

2021-05-17 23:30 UTC, evantahler commented on plugins/@grouparoo/sailthru/src/lib/client.ts
> -      // }
Please remove this comment

2021-05-18 00:09 UTC, evantahler approved these changes

2021-05-18 00:09 UTC, merged