Allow date strings in group rules for code config
grouparoo/grouparoo pull request #1828
Opened 2021-05-25 01:00 UTC by tealjulia

Previously, code config would only allow dates as numbers (epoch time) for calculated groups. 

Now, date strings can be passed and will be parsed and saved as epoch time for calculation.

TO DO: We don't currently have dates in our test suite data.  We'll need to add some to make this testable.

2021-05-26 01:19 UTC, tealjulia commented
Removed tests for date time because Javascript parses date time strings as local time.  

Accepted formats are a date string (YYYY-MM-DD which is parsed as 0:00:00.000 UTC) or a full 8601 date-time with timezone.

2021-05-27 16:01 UTC, evantahler requested changes
Good start! 

Can you please also add a test for the the relative group rules, eg: "last_purchase_date is greater than 7 days ago" (eg: they purchased something this week).  Those Group Rules look like:

```
          {
            propertyId: "last_purchase_date",
            operation: { op: "relative_gt" },
            relativeMatchNumber: 7,
            relativeMatchUnit: "days",
          },
```

2021-05-27 16:01 UTC, evantahler commented on core/__tests__/fixtures/codeConfig/group-rule-with-date/config.js
> +      ],
👍 testing a few types of date strings

2021-05-27 16:01 UTC, evantahler commented on core/src/modules/configLoaders/group.ts
> +        }
I think you are trying to determine if the user gave a timezone or not, and if not, coerce the time into UTC, to the end of the day.  I'm a little worried about this approach because there are other ways they might provide a time that are > 10 chars that will validly pass `Date.parse`, eg: `Date.parse("January 10, 2010")`.  

Perhaps you can skip this step, and instead we'll instruct people in the docs to provide a timezone + hh:mm:ss if they want to be specific, otherwise, we'll do our best.

2021-05-27 20:48 UTC, tealjulia commented
the ui test failure shouldn't be an issue once this is merged with main.  This branch doesn't have the updated version.

2021-05-27 22:22 UTC, evantahler approved these changes
Nice!

2021-05-28 00:04 UTC, merged