Objects with unused IDs are deleted from the DB before adding or updating [178122117]
grouparoo/grouparoo pull request #2265
Opened 2021-09-02 15:40 UTC by krishnaglick

2021-09-02 18:28 UTC, krishnaglick commented on core/__tests__/modules/codeConfig/codeConfig.ts
> +  TeamMember,
Organized Imports

2021-09-02 18:28 UTC, krishnaglick commented on core/src/classes/codeConfig.ts
> +    if (!configObject.id) {
Repeat logic

2021-09-02 18:28 UTC, krishnaglick commented on core/src/classes/codeConfig.ts
> +    }
This is a personal preference. Will revert if asked.

2021-09-02 18:28 UTC, krishnaglick commented on core/src/models/App.ts
> +import { Source } from "./Source";
Imports organized

2021-09-02 18:28 UTC, krishnaglick commented on core/src/models/Destination.ts
> -import { DestinationConfigurationObject } from "../classes/codeConfig";
Organized imports

2021-09-02 18:28 UTC, krishnaglick commented on core/src/models/Group.ts
> +import { Setting } from "./Setting";
Organized imports

2021-09-02 18:28 UTC, krishnaglick commented on core/src/models/Source.ts
> +import { Schedule } from "./Schedule";
Organized imports

2021-09-02 18:28 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +import { deleteTeamMembers, loadTeamMember } from "./teamMember";
Organized imports

2021-09-02 18:28 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +      profile: [],
Need all these defaults because tests got angry about `undefined` even though the types allow for it.

2021-09-02 18:28 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +export async function deleteLockedObjects(seenIds: IdsByClass) {
Types!

2021-09-02 18:28 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +  }
We could probably remove this check now that the defaults are in place.

2021-09-02 18:30 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +  }
I went to go update the type to require it all to be defined but the app got all sorts of angry. So keeping all this as-is.

2021-09-02 18:30 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +      profile: [],
Probably not worth the time to update the tests.

2021-09-02 20:04 UTC, krishnaglick commented on core/src/models/Property.ts
> +import { Source } from "./Source";
Organized imports

2021-09-02 20:05 UTC, krishnaglick commented on core/src/modules/configLoaders/index.ts
> +      agg[co.class.toLowerCase()]?.push(co.id);
Won't add unknown values!

2021-09-03 20:34 UTC, pedroslopez requested changes

2021-09-03 20:34 UTC, pedroslopez commented on core/__tests__/modules/codeConfig/codeConfig.ts
> +    test("deleted groups should not cause conflicts on create", async () => {
I don't think this test belongs in the `codeConfig` module. This probably belongs more in the model tests.

2021-09-03 20:34 UTC, pedroslopez commented on core/__tests__/modules/codeConfig/codeConfig.ts
> +      expect(config2).toMatchSnapshot();
It may be clearer to do what the other tests are doing in this file and explicitly compare that `seenIds` and `deletedIds` are as expected, for both `config` and `config2`.

2021-09-03 20:34 UTC, pedroslopez commented on core/__tests__/modules/codeConfig/codeConfig.ts
> +      }
Let's remove these logs

2021-09-03 20:34 UTC, pedroslopez commented on core/src/modules/configLoaders/index.ts
> +      agg[co.class.toLowerCase()]?.push(co.id);
Looks like we have a `cleanClass` function that's used elsewhere in this file that we can reuse here for lowercasing and trimming

2021-09-03 20:55 UTC, pedroslopez approved these changes

2021-09-03 20:56 UTC, merged