`GrouparooModel` gets state, models can be destroyed
grouparoo/grouparoo pull request #2398
Opened 2021-10-05 22:41 UTC by tealjulia

## Change description

- Adds a state column to GrouparooModel
- Adds a model:destroy task
- Adds model:destroy to the system destroy sweep task

## Related issues

Does this PR fix a Github Issue?

no

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-06 22:37 UTC, evantahler requested changes
This is really good!  

There are some minor questions/comments below.  

Once https://github.com/grouparoo/grouparoo/pull/2397 is merged in, I'll bet your tests will need to change here - there won't be any `mod_profiles` by default any more

2021-10-06 22:37 UTC, evantahler commented on core/__tests__/models/grouparooModel.ts
> +      where: { name: "test model", state: "ready" },
If models start in the 'ready' state, does the 'draft' state matter?

2021-10-06 22:37 UTC, evantahler commented on core/__tests__/modules/status.ts
> +        Model: {
Can you also please add Models Count to the stats that get reported to Telemetry?

2021-10-06 22:37 UTC, evantahler commented on core/__tests__/tasks/model/destroy.ts
> +import { helper } from "@grouparoo/spec-helper";
👍 Good testing!

2021-10-06 22:37 UTC, evantahler commented on core/src/config/routes.ts
> +        { path: "/v:apiVersion/model/:id", action: "model:destroy" },
We already have a model:destroy action (line 141)

2021-10-06 22:38 UTC, evantahler commented on core/__tests__/models/grouparooModel.ts
> +      where: { name: "test model", state: "ready" },
Maybe the UI should use `state:draft` when POSTING to the API to make a new model?

2021-10-07 13:08 UTC, teallarson commented on core/src/config/routes.ts
> +        { path: "/v:apiVersion/model/:id", action: "model:destroy" },
Oops!  I'm going to organize these a bit so I don't do that again.

2021-10-07 13:41 UTC, teallarson reviewed
@evantahler I've added the `grouparooModels` metric to the object that gets sent to Telemetry.  It looks like the way the `telemetryMetrics` table is set up, the metric will be read in as-is (no migration needed).

2021-10-07 15:34 UTC, evantahler commented
> @evantahler I've added the `grouparooModels` metric to the object that gets sent to Telemetry. It looks like the way the `telemetryMetrics` table is set up, the metric will be read in as-is (no migration needed).

Yep! The telemetry database is super-normalized, we can add more metrics without needing a migration

2021-10-07 17:32 UTC, teallarson commented on core/__tests__/models/grouparooModel.ts
> +      where: { name: "test model", state: "ready" },
At what point would it change to `state:ready` then?  We do the behavior you mentioned when creating a group, for example, because there is additional information to gather on a separate page.

I started working to implement this, but now that I've started... I am thinking of going with `ready` and `deleted` as the only two states for now.  We can add `draft` when models are at a level of complexity that we actually need it for the UI.

2021-10-07 18:20 UTC, evantahler commented on core/__tests__/models/grouparooModel.ts
> +      where: { name: "test model", state: "ready" },
👍

2021-10-07 20:18 UTC, evantahler commented on core/src/config/routes.ts
> +        { path: "/v:apiVersion/account", action: "account:view" },
❤️ Alphabetical sorting

2021-10-07 20:18 UTC, evantahler commented on core/src/models/Group.ts
> +    const model = await GrouparooModel.scope(null).findOne({
This is interesting - this is saying that it's OK to save a Group under a deleted model.  I don't think that's right

2021-10-07 20:18 UTC, evantahler commented on core/__tests__/modules/status.ts
> +        Model: {
This would need to be added to `src/modules/telemetry` to be sent, but I'll do this in another story https://www.pivotaltracker.com/story/show/179858322

2021-10-07 21:01 UTC, teallarson commented on core/src/models/Group.ts
> +    const model = await GrouparooModel.scope(null).findOne({
Good find, thank you!

2021-10-07 21:45 UTC, evantahler approved these changes

2021-10-07 21:48 UTC, merged