Config UI write correct model id on save
grouparoo/grouparoo pull request #2402
Opened 2021-10-07 20:52 UTC by krishnaglick

## Change description

> Model ID's on Source configs were not friendly.

## Related issues

Does this PR fix a Github Issue?

## Checklists

### Development

- [X] Application changes have been tested appropriately

### Impact

- [X] Code follows company security practices and guidelines
- [X] Security impact of change has been considered
- [X] Performance impact of change has been considered
- [X] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [X] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [X] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-07 21:44 UTC, evantahler requested changes
This is a good fix... but it implies that Group, GrouparooRecord, and Destination also likely have a similar problem.  Can you please check those too?

2021-10-08 13:27 UTC, krishnaglick commented
> This is a good fix... but it implies that Group, GrouparooRecord, and Destination also likely have a similar problem. Can you please check those too?
Will fix

2021-10-08 14:53 UTC, pedroslopez commented
@krishnaglick note that this only happens when the model you're assigning has been created in the same `roo config` session. If you exit out and start creating things with an existing model, you won't see it. I was trying out some things working on another story and did see the issue with groups as well

2021-10-08 16:19 UTC, bleonard commented on core/src/models/Source.ts
>      let configObject: any = {
Just above here it did `if (!appId || !name) return;`
Should that be `if (!appId || !modelId || !name) return;` ?

2021-10-08 16:23 UTC, krishnaglick commented on core/src/models/Source.ts
>      let configObject: any = {
I could have it fallback to `this.modelId`, or bail out. Whichever is fine with me.

2021-10-08 20:24 UTC, krishnaglick commented on core/__tests__/modules/configWriter.ts
> +        id: "mod_" + uuid.v4(),
This simulates config mode.

2021-10-09 00:00 UTC, bleonard approved these changes
Few changes to be clearer and some test questions, but overall good to go.

2021-10-09 00:00 UTC, bleonard commented on core/__tests__/modules/configWriter.ts
> +      expect(record.modelId).toBe("mod_profiles");
I'm suprised this isn't just `"profiles"`- unless we are in another block?
IIn that case, should we do the `uuid.v4()` thing in that block too to verify they are using the `getConfigId`?

2021-10-09 00:00 UTC, bleonard commented on core/src/models/Group.ts
> +        this.model?.getConfigId(),
just `modelId` (using the variable above)

2021-10-09 00:00 UTC, bleonard commented on core/src/models/Group.ts
> +    if (!name || !modelId) {
maybe move this up over the `const property` situation to save that work if there is `modelId`

2021-10-11 16:16 UTC, krishnaglick commented on core/__tests__/modules/configWriter.ts
> +      expect(record.modelId).toBe("mod_profiles");
It doesn't seem to be in another block. `expect(record.model.id).toBe("mod_profiles");` is green.
I'm not entirely certain why this happens yet.

2021-10-11 20:23 UTC, bleonard approved these changes

2021-10-12 16:24 UTC, evantahler approved these changes

2021-10-12 16:31 UTC, merged