migration and model for AppRefreshQuery
grouparoo/grouparoo pull request #2408
Opened 2021-10-11 15:21 UTC by teallarson

## Change description

App Refresh Query introduces a new feature on Apps.  Users can add a `"refreshQuery"` to an App's config that tells core where to scan for updated data in the App's database.  When an updated value is found, all Schedules for the App marked `"refreshEnabled: true"` (new default) will be run.  

This PR introduces the model (including migration) and codeConfig to implement this feature.

## Related issues

Does this PR fix a Github Issue?

## Checklists

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:
database migration included
>

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-11 17:55 UTC, evantahler commented on core/src/migrations/000088-createAppDataRefreshes.ts
> +        type: DataTypes.STRING(40),
191 chars!

2021-10-11 17:55 UTC, evantahler commented on core/src/migrations/000088-createAppDataRefreshes.ts
> +        allowNull: false,
allowNull should be true to allow for "draft state"

2021-10-11 17:55 UTC, evantahler commented on core/src/migrations/000088-createAppDataRefreshes.ts
> +    });
This is a new table, so you can just say `allowNull=false` above

2021-10-11 17:55 UTC, evantahler commented on core/src/models/Schedule.ts
> +  refreshEnabled: boolean;
Add this to `apiData()` as well

2021-10-11 17:55 UTC, evantahler commented on core/src/models/AppDataRefresh.ts
> +    //if instance.query was changed, run the check from appDataRefreshOps
in a `@BeforeSave` you can check `bool: instance.changed('query')` to see what is new on the instances.  Enqueue the task if it changed.

2021-10-11 17:55 UTC, evantahler commented on core/src/models/AppDataRefresh.ts
> +const STATES = ["draft", "ready", "deleted"] as const;
Probably don't need deleted state.

2021-10-11 17:55 UTC, evantahler commented
Task architecture overview https://jamboard.google.com/d/107uNQEhlgFBTLZOw6qN4RaiA54PjE7Vq9hp2CRpSoUY/viewer?f=0

2021-10-25 17:27 UTC, teallarson commented on core/src/models/AppDataRefresh.ts
> +      instance.state === "ready"
Don't validate or query anything for draft instances

2021-10-26 01:49 UTC, evantahler requested changes
This is awesome work, and it's almost there!  Good work getting all those plugin tests to pass!

The main missing topics is around the new `schedule#refreshEnabled` option - it's not used yet or considered in code-config.

2021-10-26 01:49 UTC, evantahler commented on core/src/classes/codeConfig.ts
> +  refreshQuery?: string;
I was under the impression this was going to be something like

```
refresh: {query: string, frequency: number}
```

Or is that a later story?

2021-10-26 01:49 UTC, evantahler commented on core/src/classes/codeConfig.ts
> +  refreshQuery?: string;
NVM! looking at the model and migration, that's a later story :D

2021-10-26 01:49 UTC, evantahler commented on core/__tests__/fixtures/codeConfig/initial/config.js
There's probably a test to write that checks when the refreshQuery changes, that the plugin is checked for new data

2021-10-26 01:49 UTC, evantahler commented on core/src/migrations/000088-createAppDataRefreshes.ts
> +        defaultValue: "draft",
no defaults in the DB please

2021-10-26 01:49 UTC, evantahler commented on core/src/modules/ops/appDataRefresh.ts
> +    return true;
It looks like you always return true.   What does this indicate?  Perhaps you might return `return sampleValue !== value` - which would indicate if there were changes or not?

2021-10-26 01:49 UTC, evantahler commented on core/src/models/AppDataRefresh.ts
> +      if (isUpdated === true) AppDataRefreshOps.triggerSchedules(instance);
If `AppDataRefreshOps.checkDataRefreshValue()` doesn't crash, it looks like it always returns true

2021-10-26 01:49 UTC, evantahler commented on core/src/modules/ops/appDataRefresh.ts
> +    }
This means you will run all schedules, even those that are not recurring or those with the new `refreshEnabled` column (which I don't think is used anywhere yet).

I'm guessing you might want to select all ready schedules for the source which have `refreshEnabled=true`.  If so, please add a test for that

2021-10-26 01:49 UTC, evantahler commented on core/__tests__/modules/codeConfig/codeConfig.ts
> +      });
Test a little deeper - is the query what you expect?  Is the app it belongs to correct?

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/bigquery/src/lib/appQuery.ts
> +  const rows = await connection.query(refreshQuery); // return [];
unnecessary comment

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/bigquery/src/initializers/plugin.ts
> +          methods: { test, connect, disconnect, query: appQuery },
Why the name change?  If the method is called `query`,  it would be clearer if the file was `src/lib/query.ts` returning a method called `query`.  Or, maybe the plugin method should be called `appQuery` - either way it should match I think.

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/mysql/public/templates/app/{{{id}}}.js.template
>          port: 3306,
There's probably a change missing from the source/schedule template files to use the new column `refreshEnabled`

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/mysql/src/initializers/plugin.ts
> +import { validateQuery } from "../lib/validateQuery";
Unused I think

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/mysql/src/lib/appQuery.ts
> +  const rows = await connection.asyncQuery(refreshQuery); // return [];
unnecessary comment

2021-10-26 01:49 UTC, evantahler commented on plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
> +            },
I don't think this exists on plugins?

2021-10-26 11:58 UTC, teallarson commented on core/__tests__/fixtures/codeConfig/initial/config.js
Yes.  I checked this at the model level, but it should probably be checked here as well.

2021-10-26 11:59 UTC, teallarson commented on plugins/@grouparoo/bigquery/src/initializers/plugin.ts
> +          methods: { test, connect, disconnect, query: appQuery },
To differentiate it from the `query-import` methods.  Though those are explicitly named `query-import`.

2021-10-26 17:22 UTC, teallarson commented on core/src/models/AppDataRefresh.ts
> +      if (isUpdated === true) AppDataRefreshOps.triggerSchedules(instance);
updated `AppDataRefreshOps.checkDataRefreshValue` to return `value !== originalValue`.

2021-10-26 17:27 UTC, teallarson commented on plugins/@grouparoo/bigquery/src/initializers/plugin.ts
> +          methods: { test, connect, disconnect, query: appQuery },
renamed method `appQuery`

2021-10-26 17:32 UTC, teallarson commented on plugins/@grouparoo/mysql/src/lib/appQuery.ts
> +  const rows = await connection.asyncQuery(refreshQuery); // return [];
removed from all plugins

2021-10-26 17:57 UTC, teallarson commented on plugins/@grouparoo/spec-helper/src/lib/specHelper.ts
> +            },
Correct.  Removed it.

2021-10-26 19:12 UTC, teallarson commented on core/__tests__/fixtures/codeConfig/initial/config.js
@evantahler having trouble testing it at this level.  Edit: It's not the same issue I thought, but it there is definitely weirdness going on.

2021-10-26 20:52 UTC, teallarson commented
@evantahler Should [this](https://github.com/grouparoo/grouparoo/blob/a86a643a8df0a68bb9393a2072fd3109e550e986/core/src/modules/ops/appDataRefresh.ts#L56) be calling the `ScheduleRun` Action or Task instead of directly calling the method? 

I'm stuck on these failing tests.  
- Models failure: I can see the run being created in the database (🎉), but it the test returns before the run is there it seems.  That's not great.
- Modules failure: It seems like it's tracking one step behind what I want it to... not waiting for the steps to fully complete before returning.

2021-10-28 00:50 UTC, evantahler requested changes

2021-10-28 00:50 UTC, evantahler commented on core/src/modules/configLoaders/app.ts
> +    //template placeholder is "..."
This is sort of a strange check.  We don't validate any of the other placeholders in config files (eg: password shouldn't be `"..."`) - https://github.com/grouparoo/grouparoo/blob/main/plugins/%40grouparoo/mysql/public/templates/app/%7B%7B%7Bid%7D%7D%7D.js.template#L11-L13

2021-10-28 00:50 UTC, evantahler commented on core/src/modules/configLoaders/app.ts
> +    //template placeholder is "..."
Since you are running the query onSave, if SQL doesn't like the statement, it should fail, right? - that's a strong validation.

2021-10-28 00:50 UTC, evantahler commented on core/src/modules/configLoaders/schedule.ts
> +  validateConfigObjectKeys(Schedule, configObject, ["refreshEnabled"]);
I don't think the extra `["refreshEnabled"]` is needed now that refreshEnabled is added to the Schedule model

2021-10-28 00:50 UTC, evantahler commented on core/src/modules/ops/appDataRefresh.ts
> +      }
This is going to load up and call `stop()` all all the runs for the schedule - you may want to add `state:'running'` to the where clause

2021-10-28 00:50 UTC, evantahler commented on core/src/migrations/000089-createAppDataRefreshes.ts
> +    await queryInterface.createTable("appDataRefreshes", {
(comment, doesn't need change) - this is a bit of an awkward table name (and model name).  Now that we know a little more about what this model is doing, perhaps `AppRefreshQuery` and `table: appRefreshQueries` might be clearer?

2021-10-28 00:53 UTC, teallarson commented on core/src/modules/configLoaders/app.ts
> +    //template placeholder is "..."
I'll dig into that more!  There were a handful of plugins that had failing cli-generate tests without this check.  I'd had it as `!== ""` before, which made more sense.

2021-10-28 00:55 UTC, teallarson commented on core/src/migrations/000089-createAppDataRefreshes.ts
> +    await queryInterface.createTable("appDataRefreshes", {
That makes sense.  The data its storing is all centered on the query, not the actual refreshes.

2021-10-28 15:49 UTC, evantahler approved these changes
🎉

2021-10-28 15:49 UTC, evantahler commented on core/src/modules/configLoaders/app.ts
> +  validateConfigObjectKeys(App, configObject, ["refreshQuery"]);
Was `["refreshQuery"]` needed now that that's an attribute of the model?

2021-10-28 15:49 UTC, evantahler commented on core/src/modules/ops/appRefreshQuery.ts
> +      });
👍 stopping only runs that are currently running

2021-10-28 15:53 UTC, teallarson commented on core/src/modules/configLoaders/app.ts
> +  validateConfigObjectKeys(App, configObject, ["refreshQuery"]);
Yes. `refreshQuery` is an attribute of an `AppRefreshQuery` not an `App`.  Removing it causes this error on validation:
```    
"[ config ] error with App `Data Warehouse` (data_warehouse): refreshQuery is not a valid property of a App",
```

2021-10-28 15:54 UTC, evantahler commented on core/src/modules/configLoaders/app.ts
> +  validateConfigObjectKeys(App, configObject, ["refreshQuery"]);
Makes sense!

2021-10-28 15:59 UTC, merged