Model name in list page titles
grouparoo/grouparoo pull request #2411
Opened 2021-10-11 18:45 UTC by pedroslopez

## Change description

Add model name to page titles to be clearer on what's being viewed.

![image](https://user-images.githubusercontent.com/4368928/136974451-024ab60c-2474-49fb-8641-78f7cc5634e3.png)

## Related issues

Does this PR fix a Github Issue?

No
## Checklists

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-11 19:46 UTC, evantahler requested changes
Check out `apiData()` for the models in use here - many already have `modelName` attached.  Also, please add some screenshots to the PR!

2021-10-11 19:46 UTC, evantahler commented on ui/ui-components/pages/model/[modelId]/destinations.tsx
> +  return { destinations, model, total };
For sources, destinations, (and maybe groups?) `destination.modelId` is returned along with `destination.modelName` for this purpose

2021-10-12 14:25 UTC, pedroslopez commented on ui/ui-components/pages/model/[modelId]/destinations.tsx
> +  return { destinations, model, total };
updated in 5fe3b3c to grab it from the models if possible. I still had to keep the old functionality in there because these are list views and there may not be any records, but I guess we'll avoid a request if not necessary.

2021-10-12 15:58 UTC, evantahler approved these changes

2021-10-12 16:13 UTC, merged