Improve error message collect for Zendesk plugin
grouparoo/grouparoo pull request #2425
Opened 2021-10-15 17:46 UTC by pauloouriques

- add better messages to Zendesk plugin retrieving the `result` field from the API client response.

2021-10-15 21:24 UTC, bleonard requested changes
I'd expect to see some test changes on a failed one that is checking for a better message.

2021-10-15 21:24 UTC, bleonard commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +    const errorMessage = error?.result?.toString();
what's an example of this? I'm curious if it's losing information or not. (like it used to say `422`)

2021-10-15 21:51 UTC, pauloouriques commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +    const errorMessage = error?.result?.toString();
The `errorMessage` for a 429 is: _You have exceeded the rate limit for updating a single unique user. user email: othergrouparoo@demo.com id:  external_id: grouparoo123_

2021-10-15 22:18 UTC, bleonard commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +    const errorMessage = error?.result?.toString();
That's cool. Let's verify one for a `422` as well. I think you'd sync someone with a bad or duplicate email

2021-11-16 01:34 UTC, bleonard approved these changes
Thanks!

2021-11-16 14:20 UTC, merged