Include the email on the Zendesk find user function
grouparoo/grouparoo pull request #2431
Opened 2021-10-19 01:01 UTC by pauloouriques

Lookup users by email (in addition to external_id)

2021-10-19 01:26 UTC, pauloouriques commented on plugins/@grouparoo/zendesk/__tests__/export/export-record.ts
> +    expect(user.tags.sort()).toEqual([checkboxTag, groupThree]); // including the automatically added tag.
Interesting that this test case, without the `checkboxTag` which is automatically added when the `checkbox_field = true`, start to fail after including the email on the search. So, I added the tag there.

2021-10-19 16:57 UTC, bleonard requested changes

2021-10-19 16:57 UTC, bleonard commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +    found = await searchForUser(client, { query: newEmail });
it's interesting to me this is `query` here and not `email` specifically.
The above is `external_id` specifically, which suggests there is `email`

This docs has a customer field in search: https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/

The issue with a generic `query` would be if that email address was just part of some text somewhere. It would still return that user even though it wasn't the value of their "email" field.

2021-10-19 18:04 UTC, pauloouriques commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +    found = await searchForUser(client, { query: newEmail });
I didn't find a way to perform this via API client. Then I had to do it in code.

2021-10-19 20:59 UTC, bleonard commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
> +  const email = findBy.query;
if we do have to do it this way, let's still pass in `{email}` (and not `query`) into this function and build the `query` here.

2021-10-20 20:49 UTC, bleonard commented on plugins/@grouparoo/zendesk/src/lib/export/exportRecord.ts
>          found = user;
I think we have to get rid of this code below here that throws. there might actually be more than one and that's why you are filtering to match the email.

2021-10-21 01:58 UTC, bleonard approved these changes
Looks good.

2021-10-21 02:02 UTC, bleonard commented
Definitely some weird cases here.
It seems that Zendesk was already having the desired behavior. That is' if you sent an external id and an email and there was already a user with that email and no external id, it would add the external id to the existing user.
The bug that this fixes is that we would lose existing tags on that record. Now there are persisted.

There was some struggle with finding a user by email. We tried searching for `email:name@example.com` but it seemed unreliable. I believe that was because of indexing time. Maybe Zendesk is switching to using Elasticsearch or something in those cases. What we found to be more reliable was just searching for the email. However, that could return someone who wrote an email in some other field. So we add a check in post-processing to make sure it matches.

2021-10-21 02:07 UTC, merged