add model ids to imports and exports in ui
grouparoo/grouparoo pull request #2432
Opened 2021-10-19 19:13 UTC by teallarson

## Change description

Adds the model id and a link to the model on imports and exports.
<img width="1160" alt="Screen Shot 2021-10-19 at 3 08 04 PM" src="https://user-images.githubusercontent.com/63751206/137974903-7b6a2b28-9abc-4da9-9f6a-b3c1aba88a96.png">

<img width="1171" alt="Screen Shot 2021-10-19 at 3 08 19 PM" src="https://user-images.githubusercontent.com/63751206/137974941-c7700c80-da9e-4926-b2f4-2a75ff81775e.png">

<img width="1185" alt="Screen Shot 2021-10-19 at 3 08 43 PM" src="https://user-images.githubusercontent.com/63751206/137974990-8e7df63f-bf94-423f-bb7e-5ecf257fbe9e.png">

<img width="1158" alt="Screen Shot 2021-10-19 at 3 09 01 PM" src="https://user-images.githubusercontent.com/63751206/137975037-b373b31c-df22-4719-a456-0e4f5bd07d45.png">

Imports do not track and return their sources in `apiData` like exports track and return their destinations.  Instead, I've pulled the `modelId` from the associated record and return the id with the API Data.

## Related issues

Does this PR fix a Github Issue?

no

## Checklists

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-19 19:55 UTC, teallarson commented on ui/ui-components/pages/import/[id]/edit.tsx
> +            <Link href={`/model/${_import.modelId}/edit`}>
intentionally not using the `as` here.  It was flashing a quick (~.25 second) next error with the routing when I did.

2021-10-19 20:07 UTC, evantahler requested changes
Please pre-load the Record in `imports:list` now that it will be used in `import.apiData()`
The `<Link>` comment is strange to me, but non-blocking.

2021-10-19 20:07 UTC, evantahler commented on core/src/models/Import.ts
> +    const record = await this.$get("record");
This means that we should probably pre-load the record when we get large lists of Imports, like the `imports:list` again - use an `include:[]`

2021-10-19 20:07 UTC, evantahler commented on ui/ui-components/pages/import/[id]/edit.tsx
> +            <Link href={`/model/${_import.modelId}/edit`}>
Huh! I would have expected the error flash to happen /without/ the as.  no need to change it I guess if it's working

2021-10-19 21:13 UTC, teallarson commented on core/src/models/Import.ts
> +    const record = await this.$get("record");
Added.  Ideas how to test that?  It looks like `properties:list` is the only other action using an `Includeable[]` and I don't see a test that demonstrates it.

2021-10-19 23:49 UTC, evantahler requested changes

2021-10-19 23:49 UTC, evantahler commented on core/src/actions/imports.ts
> +        },
You actually don't the `Includeable` type - it's checked for you as part of the search clause.  I think you may have added an extra where clause.

```ts
const search = {
      include: [GrouparooRecord], // since Imports `@BelongTo` GrouparooRecord the association is already handled 
      where,
      limit: params.limit,
      offset: params.offset,
      order: params.order,
    };
```

2021-10-19 23:49 UTC, evantahler commented on core/src/actions/imports.ts
> +        },
There are lots of other places using `include:[]`, like [here](https://github.com/grouparoo/grouparoo/blob/70c622aa791dfc32bb7daa78800da1a335b81815/core/src/modules/middleware/authentication.ts#L65-L68) - load teamMembers, but include the team and permissions so we can do `teamMember.team.permissions... `

2021-10-20 13:05 UTC, teallarson commented on core/src/actions/imports.ts
> +        },
Ah ha.  Sounds like I was looking in the wrong place.  Thanks.

2021-10-21 01:13 UTC, evantahler approved these changes

2021-10-21 13:50 UTC, merged