Hubspot custom objects plugin
grouparoo/grouparoo pull request #2440
Opened 2021-10-20 18:13 UTC by pauloouriques

Hubspot custom objects destination pluginin

2021-10-28 01:17 UTC, evantahler requested changes
Strong work & good tests!

I think that it's prudent to add some better types where you can for the API client response methods - things are getting complex.

Thanks for adding `destinationOptions` too! The UI looks good.
<img width="1383" alt="Screen Shot 2021-10-27 at 6 14 01 PM" src="https://user-images.githubusercontent.com/303226/139169626-d814f169-ade4-40c2-9f6d-b0f443110f43.png">

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/__tests__/export-objects/destination-mapping-options.ts
> +    };
That's cool - using Contacts as if they were custom objects

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/initializers/plugin.ts
>          ),
2 templates 👍

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/client/client.ts
> +  }
👍 helper

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/client/client.ts
>    }
Now that this client is getting rather meta - it's probably time to type some of these responses, even partially.  like, in this case we know that `data.lists` is an array of objects, and we probably know /some/ of the keys of those objects

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/client/objects.ts
> +    return response?.results || [];
Some comment about typing as above - we don't know all the properties of this object, but we do know that 

```ts
return (response?.results || []) as Array<Record<string, string | number | date>>; // I think that Hubspot objects are all 1-dimensional objects (no nested objects)
```

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export-contacts/connection.ts
> +  description: "Export Records to Hubspot and add them to Contact Lists.",
```suggestion
  description: "Export Records as Hubspot Contacts and add them to Contact Lists.",
```

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export-contacts/exportRecord.ts
> +    console.log(error.response?.data);
unnecessary?

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
> +
Nice! All 3 sync modes work on custom objects

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
> +    "Export Records to Hubspot Custom Objects and associate them with Hubspot standard objects or others custom objects.",
```suggestion
    "Export Records as Hubspot Custom Objects and associate them with Hubspot standard objects or other custom objects.",
```

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export-objects/connection.ts
> +    "Export Records to Hubspot Custom Objects and associate them with Hubspot standard objects or others custom objects.",
What do you mean by `and associate them` in this case?

2021-10-28 01:17 UTC, evantahler commented on plugins/@grouparoo/hubspot/src/lib/export/options.ts
> +  }
Nice! this will make it easy to choose the custom objects that exist

2021-10-28 01:18 UTC, evantahler commented
There's something not quite right with the `destinationOptions` - it always look like its returning the options for a `QUOTE` object.  I would expect contacts to have things like "email address" 

<img width="957" alt="Screen Shot 2021-10-27 at 6 18 06 PM" src="https://user-images.githubusercontent.com/303226/139169682-6cf6d74c-3f96-4242-b321-2948247e8f4b.png">

2021-10-28 16:13 UTC, bleonard approved these changes

2021-10-28 16:13 UTC, bleonard commented on plugins/@grouparoo/hubspot/src/lib/export-objects/destinationMappingOptions.ts
> +}> => {
Is it possible they have fields that are required for a schema?
those would go here too.

2021-10-28 23:41 UTC, pauloouriques commented on plugins/@grouparoo/hubspot/src/lib/client/objects.ts
> +    return response?.results || [];
I did it, but we could save it to do when we're moving to the new API client. What do you think?

2021-10-29 15:30 UTC, evantahler approved these changes
💥

2021-10-29 22:18 UTC, merged