Remove previously sync'd Records from Destinations when they are deleted
grouparoo/grouparoo pull request #2443
Opened 2021-10-21 19:00 UTC by evantahler

Updates GrouparooRecords to have a `deleted` state.  This allows the `record:destroy` task to enqueue one final export for any Destinations that this Record had been previously synced too.  These final exports will be `toDelete=true` explicitly.

This PR also locks in that GrouparooModels cannot be destroyed if there are still GrouparooRecords that use the model.

More or less replaces https://github.com/grouparoo/grouparoo/pull/2441

## Checklists

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

>

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2021-10-21 19:03 UTC, evantahler commented on core/__tests__/tasks/record/destroy.ts
> +    expect(record.state).toBe("deleted");
Only the "record:destroy" task should be setting the state to be deleted

2021-10-21 19:03 UTC, evantahler commented on core/src/models/GrouparooModel.ts
> +  }
GrouparooModel wasn't really using the state machine before

2021-10-21 19:03 UTC, evantahler commented on core/src/models/GrouparooModel.ts
> +    }
We should be checking that there are no records left before destroying

2021-10-21 22:23 UTC, pedroslopez requested changes
Nice, this `deleted` state makes a lot of sense. At the moment I don't think the `record:destroy` task will be enqueued again for deleted records though, so let's check that.

2021-10-21 22:23 UTC, pedroslopez commented on core/__tests__/tasks/grouparooModel/destroy.ts
> -      const app: App = await helper.factories.app();
curious about the removal of these typings... iirc the factories return `any`, is that true?

2021-10-21 22:23 UTC, pedroslopez commented on core/__tests__/tasks/grouparooModel/destroy.ts
> +      // remove group
```suggestion
      // remove record
```

2021-10-21 22:23 UTC, pedroslopez commented on core/__tests__/tasks/record/destroy.ts
> +    // record is still there, but is now being exported
we could also add a check to ensure that the export is a `toDelete: true` both here and on the group destination test

2021-10-21 22:23 UTC, pedroslopez commented on core/src/models/GrouparooModel.ts
> +    const records = await GrouparooRecord.unscoped().count({
oh! never seen this `unscoped()` thing before

2021-10-21 22:23 UTC, pedroslopez commented on core/src/tasks/record/destroy.ts
> +    if (["draft", "pending", "ready"].includes(record.state)) {
if the record is `pending`, should we wait until it's done importing?

2021-10-21 22:25 UTC, pedroslopez requested changes

2021-10-21 22:25 UTC, pedroslopez commented on core/src/tasks/record/destroy.ts
> +      await record.update({ state: "deleted" });
whoops, didnt submit this with the review:

I believe this `record:destroy` task is only enqueued if the records are `ready` and match a few conditions - if we now have to enqueue it for `deleted` records as well, the `getRecordsToDestroy` function will need to be updated, but I'm not seeing any changes to it in this PR.

2021-10-21 22:27 UTC, evantahler commented on core/__tests__/tasks/grouparooModel/destroy.ts
> -      const app: App = await helper.factories.app();
As of about a week ago, the factories now properly return the types!  
I haven't gone through the test suite and updated them all, I'm just removing extraneous types as I find them as it's not a problem since the types match

2021-10-21 22:29 UTC, pedroslopez commented on core/__tests__/tasks/grouparooModel/destroy.ts
> -      const app: App = await helper.factories.app();
oh that's great!

2021-10-22 00:45 UTC, evantahler commented on core/src/tasks/record/destroy.ts
> +      await record.update({ state: "deleted" });
OH... thanks!

Added.

2021-10-22 00:45 UTC, evantahler commented on core/src/tasks/record/destroy.ts
> +    if (["draft", "pending", "ready"].includes(record.state)) {
`getRecordsToDestroy()` won't include `pending` or `draft` records... so I guess not!

2021-10-22 17:37 UTC, bleonard approved these changes

2021-10-22 17:37 UTC, bleonard commented on core/src/models/GrouparooRecord.ts
>    async buildNullProperties(state: GrouparooRecord["state"] = "pending") {
when does this get called? What does throwing here end up doing?

2021-10-22 17:37 UTC, bleonard commented on core/src/models/GrouparooRecord.ts
> +      force,
@pedroslopez using force here, so might have a conflict with your work.

2021-10-22 17:40 UTC, pedroslopez commented on core/src/models/GrouparooRecord.ts
> +      force,
Should be ok, this is forcing the exports, not the group/model runs

2021-10-22 17:53 UTC, evantahler commented on core/src/models/GrouparooRecord.ts
>    async buildNullProperties(state: GrouparooRecord["state"] = "pending") {
This gets called by a few places: on creating the record, after an import, when new properties are created, etc.
While it seems save in the test, I'll remove the throw here, it's fine to make null properties again if the profile is deleted

2021-10-22 19:04 UTC, pedroslopez approved these changes

2021-10-22 19:08 UTC, merged