Redirect to the record/edit page in community edition
grouparoo/grouparoo pull request #2783
Opened 2022-01-11 01:31 UTC by evantahler

Allows the `/object/id` redirect page to take users to Record detail pages in UI-Community

## Checklists

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

2022-01-11 01:32 UTC, evantahler commented on ui/ui-components/pages/object/[id].tsx
> +        router.replace(`/${singular(table)}/${id}/${detailPage}`);
Also using `router.replace()` rather than `router.push()` to remove the object page from the browser history

2022-01-11 15:30 UTC, pedroslopez requested changes
Nice, just one small thing to fix

2022-01-11 15:30 UTC, pedroslopez commented on ui/ui-components/pages/object/[id].tsx
> +    const table = response.records[0].tableName.toLowerCase();
`records[0]` is being accessed before the length check, which would cause a `TypeError` if an object with that ID doesn't exist

2022-01-12 14:03 UTC, pedroslopez approved these changes

2022-01-12 14:36 UTC, edmundito commented
Note that I made a change in #2771 that will conflict with this logic. I had the same question myself when I refactored this to make it work without a global `modelId`. What I'd suggest is to close this PR and I can ensure that record redirects to the record page in the community edition in my branch.

2022-01-12 17:56 UTC, evantahler commented
ah! Ok @edmundito - I'll close this PR then.  Thanks!

2022-01-12 17:57 UTC, closed without merging

2022-01-12 18:12 UTC, bleonard commented
Here are the edit pages in community in case it's helpful
```
➜  pages git:(main) ✗ pwd                   
/Users/brian/grouparoo/grouparoo/ui/ui-community/pages
➜  pages git:(main) ✗ find . | grep edit.tsx
./notification/[id]/edit.tsx
./teamMember/[id]/edit.tsx
./model/[modelId]/record/[recordId]/edit.tsx
./exportProcessor/[id]/edit.tsx
./run/[id]/edit.tsx
./export/[id]/edit.tsx
./import/[id]/edit.tsx
```