Snowflake Source
grouparoo/grouparoo pull request #784
Opened 2020-09-28 23:10 UTC by bleonard

Connect to snowflake to pull in data.

2020-09-28 23:11 UTC, bleonard commented
Also refactored SQL connection code to share amongst big query, postgres, redshift, mysql, and friends.

2020-09-28 23:21 UTC, bleonard commented
Close T-539

2020-09-30 17:58 UTC, evantahler requested changes
There's one thing to fix in the redshift plugin.

I really like the seperation/organization you've got here.  Perhaps in the near future there's a refactor in which we make a `@grouparoo/database-base` plugin which has a lot of these methods which PG/mySQL,Snowflake,etc can extend?

2020-09-30 17:58 UTC, evantahler commented on plugins/@grouparoo/redshift/README.md
> +# @Grouparoo/Snowflake
Looks like you changed the wrong file

2020-09-30 17:58 UTC, evantahler commented on plugins/@grouparoo/snowflake/__tests__/utils/nockHelper.ts
> +    }
Dang!   That's a crazy API snowflake has.  I guess... they don't trust HTTP compression?

2020-09-30 17:58 UTC, evantahler commented on plugins/@grouparoo/snowflake/src/lib/connect.ts
> +  client.schemaName = schema;
just a note that you can do this to bypass the TS warnings:

```ts
client['schemaName'] = schema;
```

2020-09-30 19:17 UTC, bleonard commented
> I really like the seperation/organization you've got here. Perhaps in the near future there's a refactor in which we make a @grouparoo/database-base plugin which has a lot of these methods which PG/mySQL,Snowflake,etc can extend?

Yes, I wanted to discuss with you the "core" or "base-plugin" thoughts for this source code, some stuff in destinations, and generic stuff (caching).

2020-10-01 00:05 UTC, evantahler approved these changes

2020-10-01 00:14 UTC, merged

2020-10-09 01:27 UTC, evantahler commented
Closes https://github.com/grouparoo/grouparoo/issues/652