Create CODE_OF_CONDUCT.md
grouparoo/grouparoo pull request #87
Opened 2020-04-30 22:14 UTC by evantahler

Generated with help by Github.

2020-04-30 22:20 UTC, bleonard commented
👍

2020-04-30 22:28 UTC, bleonard approved these changes

2020-05-01 17:07 UTC, bleonard approved these changes

2020-05-01 17:07 UTC, bleonard commented on .github/CONTRIBUTING.md
> +At this time, Grouparoo Inc. is focused on expanding and enhancing our core features, in addition to developing our paid plugins. With that in mind, there are some areas of the codebase that may not
I think "check in with us on slack, first, if you have an idea" at the end of this would be good.

2020-05-01 17:18 UTC, andyjih requested changes
Looks great! Just a typo :)

2020-05-01 17:18 UTC, andyjih commented on .github/CONTRIBUTING.md
> +Grouparoo is a large project with lost of different plugins and tools. We don't expect you to know about everything, so that's why we have a robust test suite. This allows us to ensure that no matter
"lost" -> "lots"

2020-05-01 19:03 UTC, andyjih approved these changes

2020-05-01 19:38 UTC, merged